// <auto-generated />
using System;
using ContactlessLoyaltyWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactlessLoyaltyWebApp.Migrations
{
    [DbContext(typeof(LoyaltyDatabaseContext))]
    [Migration("20200703021321_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactlessLoyaltyWebApp.Models.LoyaltyCardModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastStampReceived")
                        .HasColumnType("datetime2")
                        .HasMaxLength(50);

                    b.Property<int>("StampsCollected")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VoucherReceived")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("LoyaltyCards");
                });

            modelBuilder.Entity("ContactlessLoyaltyWebApp.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CardID")
                        .HasColumnType("int");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("CardID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ContactlessLoyaltyWebApp.Models.LoyaltyCardModel", b =>
                {
                    b.HasOne("ContactlessLoyaltyWebApp.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("ContactlessLoyaltyWebApp.Models.UserModel", b =>
                {
                    b.HasOne("ContactlessLoyaltyWebApp.Models.LoyaltyCardModel", "LoyaltyCard")
                        .WithMany()
                        .HasForeignKey("CardID");
                });
#pragma warning restore 612, 618
        }
    }
}
